# Generated by Django 3.0.2 on 2020-02-19 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('active_sprint', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('sprint_count', models.IntegerField()),
                ('description', models.TextField()),
                ('story_point', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('release_version', models.CharField(max_length=100)),
                ('tag_1', models.CharField(max_length=100)),
                ('tag_2', models.CharField(max_length=1000)),
            ],
        ),
    ]
