# Generated by Django 3.0.3 on 2020-05-09 05:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='SprintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=False)),
                ('is_closed', models.BooleanField(default=False)),
                ('project_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_board_api.ProjectInfo')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('story_point', models.PositiveSmallIntegerField()),
                ('kind', models.CharField(max_length=100)),
                ('order', models.IntegerField()),
                ('release_version', models.CharField(blank=True, max_length=100)),
                ('tag_1', models.CharField(blank=True, max_length=100)),
                ('tag_2', models.CharField(blank=True, max_length=1000)),
                ('status', models.IntegerField(default=1)),
                ('sprint_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='kanban_board_api.SprintInfo')),
            ],
        ),
    ]
