# Generated by Django 3.0.3 on 2020-03-05 13:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board_api', '0002_auto_20200305_1314'),
    ]

    operations = [
        migrations.CreateModel(
            name='SprintInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('is_closed', models.BooleanField(default=False)),
            ],
        ),
        migrations.RemoveField(
            model_name='projectinfo',
            name='active_sprint',
        ),
        migrations.RemoveField(
            model_name='ticket',
            name='sprint_count',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='active_sprint_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='kanban_board_api.SprintInfo'),
        ),
        migrations.AddField(
            model_name='ticket',
            name='sprint_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanban_board_api.SprintInfo'),
            preserve_default=False,
        ),
    ]
