# Generated by Django 3.0.3 on 2020-03-05 14:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board_api', '0003_auto_20200305_1359'),
    ]

    operations = [
        migrations.RenameField(
            model_name='ticket',
            old_name='sprint_id',
            new_name='sprint',
        ),
    ]
