# Generated by Django 3.0.3 on 2020-03-07 07:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board_api', '0004_auto_20200305_1433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectinfo',
            name='active_sprint_id',
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='project_name',
            field=models.CharField(default='aa', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sprintinfo',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sprintinfo',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='kanban_board_api.ProjectInfo'),
            preserve_default=False,
        ),
    ]
