# Generated by Django 3.0.3 on 2020-03-07 08:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board_api', '0005_auto_20200307_0735'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sprintinfo',
            old_name='project',
            new_name='project_id',
        ),
        migrations.RenameField(
            model_name='ticket',
            old_name='sprint',
            new_name='sprint_id',
        ),
    ]
