# Generated by Django 3.0.3 on 2020-04-05 07:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kanban_board_api', '0006_auto_20200307_0814'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='sprintinfo',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
    ]
